# Site settings
baseURL = "//benmateev.com"
languageCode = "en-US"
title = "Benjamin Mateev"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-1137676-7"

# Copyright
copyright = "&copy;2020 Benjamin Mateev"

[params]

  # Metadata for search engines and social sharing
  author = "Benjamin Mateev"
  description = "Learn. Reflect. Create. Grow."
  shareImage = "images/background.jpg"
  twitterHandle = "benjaminmateev"

  # Favicon
  favicon = ""

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background-new.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:benjamin.mateev@gmail.com"
      [[params.links.list1.link]]
        text = "Meet me"
        url = "https://calendly.com/mateev/30min"
      [[params.links.list1.link]]
        text = "Writing"
        url = "https://medium.com/@benjaminmateev"
      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/benjaminmateev"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/benjamin.mateev"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/benjaminmateev/"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/benjaminmateev"

        [[params.links.list2.link]]
        text = "Goodreads"
        url = "https://www.goodreads.com/user/show/83860601-benjamin-mateev"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Reality"
        url = "https://www.schusterman.org/jewish-community-and-israel/signature-initiatives/reality-experience"
      
      [[params.links.list3.link]]
        text = "Starting Bloc"
        url = "http://startingbloc.org/"

      [[params.links.list3.link]]
        text = "Defining the next Decade"
        url = "http://definingthenextdecade.com/"

      [[params.links.list3.link]]
        text = "Sandbox"
        url = "https://sandbox.is/"
        