# Site settings
baseURL = "//benmateev.com"
languageCode = "en-US"
title = "Benjamin Mateev"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Benjamin Mateev"

[params]

  # Metadata for search engines and social sharing
  author = "Benjamin Mateev"
  description = ""
  shareImage = "images/background.jpg"
  twitterHandle = "benjaminmateev"

  # Favicon
  favicon = ""

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:benjamin.mateev@gmail.com"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://medium.com/@benjaminmateev"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/benjaminmateev"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/benjamin.mateev"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/benjaminmateev/"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/benjaminmateev"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Reality"
        url = "https://www.schusterman.org/jewish-community-and-israel/signature-initiatives/reality-experience"
      
      [[params.links.list3.link]]
        text = "Starting Bloc"
        url = "http://startingbloc.org/"

      [[params.links.list3.link]]
        text = "Defining the next Decade"
        url = "http://definingthenextdecade.com/"

      [[params.links.list3.link]]
        text = "EYES"
        url = "http://eyesinternational.org/"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
